### PR TITLE
fix(bqetl): Fix a bug in `bigquery_etl.pytest_plugin.routine.RoutineFile`

### PR DESCRIPTION
**Pull request by sean-rose**
## Description
pytest was failing with `AttributeError: 'NoneType' object has no attribute 'parent'` while trying to collect tests for our user-defined routines.

This issue may have been introduced by #7127.

## Related Tickets & Documents
* https://github.com/mozilla/bigquery-etl/pull/7127

**Reviewer, please follow [this checklist](https://github.com/mozilla/bigquery-etl/blob/main/.github/reviewer_checklist.md)**

### CODE REVIEW

**Comment by sean-rose** [comment]
Never mind, I just hadn't updated my local venv to use the newer version of pytest. 🤦
